### ISSUE TITLE
Graphics problems with Matrox Mystique

### ISSUE THREAD

**Issue by K33N0K** [mills32/Little-Game-Engine-for-VGA-EGA#7]
Hello Dudes. I am using a VESA 2.0 Matrox Mystique. The scrolling stutters sometimes and flickers. Can you do something about that? 

Greets, N0k

**Comment by mills32** [comment]
I have to add scrolling compatible with different cards/CPUS. This engine is designed for very very slow CPUS which need the hardware scrolling, every VGA compatible card behaves different when using the hardware scroll, but is the CPU is very slow, it ussualy works OK. 

I'm considering changing the engine so that fast cpus just redraw everything and don't use any hardware scroll.

**Comment by mills32** [comment]
I added another scrolling function, it should work well on all cards

**Comment by K33N0K** [comment]
Ohh MAN! NICE! i was already in bed because I have to work tomorrow. but wow! I have to test this now.

**Comment by K33N0K** [comment]
alright, what i can report so far is the engine run's smooth on VESA 1.0 card for now. vesa 2.0 (maybe it's a matrox related problem) still the same. do u have something i can upload a video? because i also have a capture card for "stream" dos stuff.
